In [2]:
import pandas as pd 
import numpy as np
heart = pd.read_csv("data/heart.csv") # IMPORT THE DATASET
print(heart)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2     

In [3]:
# SPLLITING DATASET
attribute = ['age','sex','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal']
x=heart[attribute]
# print(x)
y=heart.target
# print(y)

In [4]:
from sklearn.feature_selection import  SelectKBest,f_classif
from numpy import set_printoptions
# feature extraction
test = SelectKBest(score_func=f_classif, k=4)
fit = test.fit(x,y)
# summarize scores
set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(x)
# summarize selected features
print(features[0:5,:])

[16.117 25.792  6.458  2.203  0.237  5.777 65.12  70.952 68.551 40.902
 54.56  40.408]
[[150.    0.    2.3   0. ]
 [187.    0.    3.5   0. ]
 [172.    0.    1.4   0. ]
 [178.    0.    0.8   0. ]
 [163.    1.    0.6   0. ]]


In [5]:
from sklearn.feature_selection import  SelectKBest,f_classif
from numpy import set_printoptions
# feature extraction
test = SelectKBest(score_func=f_classif, k=6) # k value can be changed if required 
fit = test.fit(x,y)
# summarize scores
set_printoptions(precision=7)                 # precision value can be changed if required 
print(fit.scores_)
features = fit.transform(x)
# summarize selected features 
print(features[0:7,:])                        # ratio value can be changed if required 

[16.1166998 25.7921912  6.4581687  2.2029834  0.2369423  5.7772089
 65.1201044 70.9524382 68.5514394 40.9020706 54.5598338 40.4076961]
[[150.    0.    2.3   0.    0.    1. ]
 [187.    0.    3.5   0.    0.    2. ]
 [172.    0.    1.4   2.    0.    2. ]
 [178.    0.    0.8   2.    0.    2. ]
 [163.    1.    0.6   2.    0.    2. ]
 [148.    0.    0.4   1.    0.    1. ]
 [153.    0.    1.3   1.    0.    2. ]]


In [6]:
from sklearn.feature_selection import  SelectKBest,f_classif
from numpy import set_printoptions
# feature extraction

test = SelectKBest(score_func=f_classif, k=9) # k value can be changed if required 
fit = test.fit(x,y)

# summarize scores

set_printoptions(precision=10)                 # precision value can be changed if required 
print(fit.scores_)
features = fit.transform(x)

# summarize selected features 
print(features[5:10,:6])                        # ratio value can be changed if required 

[16.1166998232 25.7921911538  6.458168674   2.2029834464  0.2369423359
  5.7772089052 65.1201044012 70.9524382164 68.5514394103 40.9020706285
 54.5598337958 40.4076961495]
[[ 57.    1.  140.  148.    0.    0.4]
 [ 56.    0.  140.  153.    0.    1.3]
 [ 44.    1.  120.  173.    0.    0. ]
 [ 52.    1.  172.  162.    0.    0.5]
 [ 57.    1.  150.  174.    0.    1.6]]
