In [1]:
import pandas as pd 
import numpy as np
heart = pd.read_csv("data/heart.csv") # IMPORT THE DATASET
print(heart)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2     

In [2]:
# SPLLITING DATASET
attribute = ['age','sex','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal']
x=heart[attribute]
# print(x)
y=heart.target
# print(y)

In [3]:
#univarient feature selection- variance threshold
from sklearn.feature_selection import VarianceThreshold
selector= VarianceThreshold(threshold=0.0) #threshold value can be changed
selector.fit_transform(x,y)

array([[ 63.,   1., 145., ...,   0.,   0.,   1.],
       [ 37.,   1., 130., ...,   0.,   0.,   2.],
       [ 41.,   0., 130., ...,   2.,   0.,   2.],
       ...,
       [ 68.,   1., 144., ...,   1.,   2.,   3.],
       [ 57.,   1., 130., ...,   1.,   1.,   3.],
       [ 57.,   0., 130., ...,   1.,   1.,   2.]])

In [4]:
#univarient feature selection- variance threshold
from sklearn.feature_selection import VarianceThreshold
selector= VarianceThreshold(threshold=10.2) #threshold value can be changed
selector.fit_transform(x,y)

array([[ 63., 145., 233., 150.],
       [ 37., 130., 250., 187.],
       [ 41., 130., 204., 172.],
       ...,
       [ 68., 144., 193., 141.],
       [ 57., 130., 131., 115.],
       [ 57., 130., 236., 174.]])

In [5]:
#univarient feature selection- variance threshold
from sklearn.feature_selection import VarianceThreshold
selector= VarianceThreshold(threshold=-5.7) #threshold value can be changed
selector.fit_transform(x,y)

array([[ 63.,   1., 145., ...,   0.,   0.,   1.],
       [ 37.,   1., 130., ...,   0.,   0.,   2.],
       [ 41.,   0., 130., ...,   2.,   0.,   2.],
       ...,
       [ 68.,   1., 144., ...,   1.,   2.,   3.],
       [ 57.,   1., 130., ...,   1.,   1.,   3.],
       [ 57.,   0., 130., ...,   1.,   1.,   2.]])